# Generated by Django 4.1.5 on 2023-01-19 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Nama Lengkap')),
                ('nik', models.IntegerField(max_length=50, verbose_name='NIK')),
                ('gender', models.CharField(max_length=15, verbose_name='Jenis Kelamin')),
                ('place_birth', models.CharField(max_length=255, verbose_name='Tempat Lahir')),
                ('date_birth', models.CharField(max_length=255, verbose_name='Tanggal Lahir')),
                ('month_birth', models.CharField(max_length=255, verbose_name='Bulan Lahir')),
                ('tahun_birth', models.CharField(max_length=255, verbose_name='Tahun Lahir')),
                ('religion', models.CharField(max_length=255, verbose_name='Agama')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.IntegerField(max_length=20, verbose_name='No HP')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('postal_code', models.IntegerField(max_length=5, verbose_name='Postal Code')),
                ('province', models.CharField(max_length=255, verbose_name='province')),
                ('districts', models.CharField(max_length=255, verbose_name='districts')),
                ('sub_districts', models.CharField(max_length=255, verbose_name='sub_districts')),
                ('last_education', models.CharField(max_length=255, verbose_name='last_education')),
                ('school_name', models.CharField(max_length=255, verbose_name='school_name')),
                ('school_address', models.CharField(max_length=255, verbose_name='school_address')),
                ('firt_opt', models.CharField(max_length=50, verbose_name='Pilihan Pertama')),
                ('second_opt', models.CharField(max_length=50, verbose_name='Pilihan Kedua')),
                ('last_opt', models.CharField(max_length=50, verbose_name='Pilihan Terakhir')),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
