# Generated by Django 4.1.5 on 2023-01-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='firt_opt',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='last_education',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='last_opt',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='month_birth',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='place_birth',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='second_opt',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='sub_districts',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='tahun_birth',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='addr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='dateBirth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tanggal Lahir'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='firtOpt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pilihan Pertama'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='lastEdu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last_education'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='lastOpt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pilihan Terakhir'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='monthBirth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bulan Lahir'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='phoneNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='No HP'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='placeBirth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempat Lahir'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='postalCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='Postal Code'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='schoolAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='school_address'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='schoolName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='school_name'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='secondOpt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pilihan Kedua'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='subDistricts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sub_districts'),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='tahunBirth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tahun Lahir'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='districts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='districts'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='nik',
            field=models.IntegerField(blank=True, null=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='religion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agama'),
        ),
    ]
