# Generated by Django 4.1.5 on 2023-01-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_full_name_studentmodel_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='firtOpt',
            new_name='firstOpt',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='schoolAddress',
            new_name='schoolAddr',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='tahunBirth',
            new_name='yearBirth',
        ),
    ]
