# Generated by Django 4.1.5 on 2023-01-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_firtopt_studentmodel_firstopt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='nik',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phoneNumber',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='No HP'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='postalCode',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Postal Code'),
        ),
    ]
