# Generated by Django 4.1.5 on 2023-01-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_studentmodel_nik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="username"
            ),
        ),
    ]
