# Generated by Django 4.1.5 on 2023-01-26 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_studentmodel_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="last_login",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
