# Generated by Django 4.1.5 on 2023-01-27 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_studentmodel_registered_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentmodel",
            name="registered_at",
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="registered_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 1, 27, 0, 45, 33, 251722, tzinfo=datetime.timezone.utc
                ),
                editable=False,
                verbose_name="Terdaftar Sejak",
            ),
        ),
    ]
