# Generated by Django 4.1.5 on 2023-01-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_studentmodel_registered_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="registered_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Terdaftar Sejak"),
        ),
    ]
